/* prjParams.h - dynamically generated configuration header */


/*
GENERATED: Fri Jun 28 15:40:42 +0530 2019
DO NOT EDIT - file is regenerated whenever the project changes
*/

#ifndef INCprjParamsh
#define INCprjParamsh


/*** INCLUDED COMPONENTS ***/

#define INCLUDE_ADR_SPACE_LIB
#define INCLUDE_ADR_SPACE_LIB_ARCH
#define INCLUDE_ADR_SPACE_SHELL_CMD
#define INCLUDE_ADR_SPACE_SHOW
#define INCLUDE_ANSI_ABORT
#define INCLUDE_ANSI_ABS
#define INCLUDE_ANSI_ASSERT
#define INCLUDE_ANSI_ATOF
#define INCLUDE_ANSI_BSEARCH
#define INCLUDE_ANSI_CTYPE
#define INCLUDE_ANSI_LOCALE
#define INCLUDE_ANSI_LONGJMP
#define INCLUDE_ANSI_MATH
#define INCLUDE_ANSI_MEMCHR
#define INCLUDE_ANSI_MEMCMP
#define INCLUDE_ANSI_MEMCPY
#define INCLUDE_ANSI_MEMMOVE
#define INCLUDE_ANSI_MEMSET
#define INCLUDE_ANSI_STDIO
#define INCLUDE_ANSI_STDIO_EXTRA
#define INCLUDE_ANSI_STDLIB
#define INCLUDE_ANSI_STDLIB_NUMBERS
#define INCLUDE_ANSI_STRCASECMP
#define INCLUDE_ANSI_STRCAT
#define INCLUDE_ANSI_STRCMP
#define INCLUDE_ANSI_STRCPY
#define INCLUDE_ANSI_STRDUP
#define INCLUDE_ANSI_STRERROR
#define INCLUDE_ANSI_STRING
#define INCLUDE_ANSI_STRLCPY
#define INCLUDE_ANSI_STRLEN
#define INCLUDE_ANSI_STRNCASECMP
#define INCLUDE_ANSI_STRNCAT
#define INCLUDE_ANSI_STRNCMP
#define INCLUDE_ANSI_STRNCPY
#define INCLUDE_ANSI_STRTOD
#define INCLUDE_ANSI_TIME
#define INCLUDE_APPL_LOG_UTIL
#define INCLUDE_ATOMIC_OPERATORS
#define INCLUDE_AUX_CLK
#define INCLUDE_AVL_UINT_TREES
#define INCLUDE_BASE_KERNEL
#define INCLUDE_BLIB
#define INCLUDE_BMPLIB
#define INCLUDE_BOOT_LINE_INIT
#define INCLUDE_BSP_MACROS
#define INCLUDE_CACHE_ENABLE
#define INCLUDE_CACHE_SUPPORT
#define INCLUDE_CHECKSUM
#define INCLUDE_CLASS_LIB
#define INCLUDE_CLASS_LIST
#define INCLUDE_CLASS_SHOW
#define INCLUDE_COMMON_NET
#define INCLUDE_COPROCESSOR
#define INCLUDE_COPROCESSOR_SHOW
#define INCLUDE_CPLUS
#define INCLUDE_CPLUS_DEMANGLER
#define INCLUDE_CPLUS_LANG
#define INCLUDE_CPU_LIGHT_PWR_MGR
#define INCLUDE_CTORS_DTORS
#define INCLUDE_DATACOLLECTOR
#define INCLUDE_DEBUG
#define INCLUDE_DEBUG_SHELL_CMD
#define INCLUDE_DEFERRED_INTERRUPT_ENABLE
#define INCLUDE_DEVICE_MANAGER
#define INCLUDE_DISK_UTIL
#define INCLUDE_DISK_UTIL_SHELL_CMD
#define INCLUDE_DLL
#define INCLUDE_EDR_ERRLOG
#define INCLUDE_EDR_PM
#define INCLUDE_EDR_POLICY_HOOKS
#define INCLUDE_EDR_SHELL_CMD
#define INCLUDE_EDR_SHOW
#define INCLUDE_EDR_STUB
#define INCLUDE_EDR_SYSDBG_FLAG
#define INCLUDE_END
#define INCLUDE_END_COMMON
#define INCLUDE_END_ETHER_HDR
#define INCLUDE_ENV_VARS
#define INCLUDE_ERF
#define INCLUDE_EVENTPOINT
#define INCLUDE_EVENTPOINT_STUB
#define INCLUDE_EXC_HANDLING
#define INCLUDE_EXC_SHOW
#define INCLUDE_EXC_TASK
#define INCLUDE_FLOATING_POINT
#define INCLUDE_FORMATTED_IO
#define INCLUDE_FORMATTED_OUT_BASIC
#define INCLUDE_FP_TYPE
#define INCLUDE_FS_EVENT_UTIL
#define INCLUDE_FS_MONITOR
#define INCLUDE_FTP
#define INCLUDE_GETOPT
#define INCLUDE_GNU_INTRINSICS
#define INCLUDE_HANDLE_SHOW
#define INCLUDE_HASH
#define INCLUDE_HOOKS
#define INCLUDE_HOOK_SHOW
#define INCLUDE_HOST_TBL
#define INCLUDE_HOST_TBL_SYSCTL
#define INCLUDE_HW_FP
#define INCLUDE_HW_FP_MREGS
#define INCLUDE_HW_FP_SHOW
#define INCLUDE_IO_BASIC
#define INCLUDE_IO_FILE_SYSTEM
#define INCLUDE_IO_MISC
#define INCLUDE_IO_POSIX
#define INCLUDE_IO_REMOVABLE
#define INCLUDE_IO_RTP
#define INCLUDE_IO_SYSTEM
#define INCLUDE_IPAIP
#define INCLUDE_IPAIP_GLOBAL_CONFIGS
#define INCLUDE_IPCOM
#define INCLUDE_IPCOM_SHELL_CMD
#define INCLUDE_IPCOM_USE_ETHERNET
#define INCLUDE_IPCOM_USE_INET
#define INCLUDE_IPCOM_USR
#define INCLUDE_IPIFCONFIG_CMD
#define INCLUDE_IPNET
#define INCLUDE_IPNET_IFCONFIG_1
#define INCLUDE_IPNET_LOOPBACK_CONFIG
#define INCLUDE_IPNET_SOCKET
#define INCLUDE_IPNET_STACK
#define INCLUDE_IPNET_SYSCTL
#define INCLUDE_IPNET_USE_LOOPBACK
#define INCLUDE_IPNET_USE_ROUTESOCK
#define INCLUDE_IPNET_USE_SOCK_COMPAT
#define INCLUDE_IPPROXYARP
#define INCLUDE_IPTCP
#define INCLUDE_IPV4
#define INCLUDE_IPWRAP_IFCONFIG
#define INCLUDE_IPWRAP_INETLIB
#define INCLUDE_IPWRAP_IPPROTO
#define INCLUDE_JOB_DEFER
#define INCLUDE_JOB_QUEUE
#define INCLUDE_JOB_TASK
#define INCLUDE_KERNEL
#define INCLUDE_KERNEL_ARCH
#define INCLUDE_KERNEL_COMMON_HEAP
#define INCLUDE_KERNEL_HARDENING
#define INCLUDE_KERNEL_PROXIMITY_HEAP
#define INCLUDE_LINKBUFPOOL
#define INCLUDE_LOADER
#define INCLUDE_LOADER_CODE
#define INCLUDE_LOADER_HOOKS
#define INCLUDE_LOGGING
#define INCLUDE_LSTLIB
#define INCLUDE_MBUF_UTIL1
#define INCLUDE_MEMORY_CONFIG
#define INCLUDE_MEM_MGR_BASIC
#define INCLUDE_MEM_MGR_FULL
#define INCLUDE_MEM_MGR_INFO
#define INCLUDE_MEM_RTP
#define INCLUDE_MEM_SHOW
#define INCLUDE_MMAP
#define INCLUDE_MMU_BASIC
#define INCLUDE_MMU_GLOBAL_MAP
#define INCLUDE_MODULE_MANAGER
#define INCLUDE_MODULE_SHELL_CMD
#define INCLUDE_MSG_Q
#define INCLUDE_MSG_Q_CREATE_DELETE
#define INCLUDE_MSG_Q_EVENTS
#define INCLUDE_MSG_Q_INFO
#define INCLUDE_MSG_Q_OPEN
#define INCLUDE_MSG_Q_SHOW
#define INCLUDE_MUX
#define INCLUDE_MUX2
#define INCLUDE_MUX2_OVER_END
#define INCLUDE_MUXTK
#define INCLUDE_MUXTK_OVER_END
#define INCLUDE_MUX_COMMON
#define INCLUDE_NETBUFLIB
#define INCLUDE_NETBUFPOOL
#define INCLUDE_NETMASK_GET
#define INCLUDE_NETWORK
#define INCLUDE_NET_BOOT
#define INCLUDE_NET_DAEMON
#define INCLUDE_NET_DRV
#define INCLUDE_NET_HOST_SETUP
#define INCLUDE_NET_REM_IO
#define INCLUDE_NET_SYSCTL
#define INCLUDE_OBJECT_SHOW
#define INCLUDE_OBJ_INFO
#define INCLUDE_OBJ_LIB
#define INCLUDE_OBJ_OPEN
#define INCLUDE_OBJ_OWNERSHIP
#define INCLUDE_OFFSET_SYMBOLS
#define INCLUDE_PAGE_SIZE_OPTIMIZATION
#define INCLUDE_PASSFS
#define INCLUDE_PASSFS_SYM_TBL
#define INCLUDE_PG_MGR_BASIC
#define INCLUDE_PG_MGR_LIB
#define INCLUDE_PG_MGR_SHOW
#define INCLUDE_PG_POOL_LIB
#define INCLUDE_PG_POOL_PHYS_LIB
#define INCLUDE_PG_POOL_SHOW
#define INCLUDE_PG_POOL_VIRT_LIB
#define INCLUDE_PIPES
#define INCLUDE_POOL
#define INCLUDE_POSIX_AIO
#define INCLUDE_POSIX_AIO_SHOW
#define INCLUDE_POSIX_AIO_SYSDRV
#define INCLUDE_POSIX_CLOCKS
#define INCLUDE_POSIX_DIRLIB
#define INCLUDE_POSIX_FS
#define INCLUDE_POSIX_FTRUNC
#define INCLUDE_POSIX_MAPPED_FILES
#define INCLUDE_POSIX_MEM
#define INCLUDE_POSIX_MQ
#define INCLUDE_POSIX_MQ_SHOW
#define INCLUDE_POSIX_PTHREADS
#define INCLUDE_POSIX_SCHED
#define INCLUDE_POSIX_SEM
#define INCLUDE_POSIX_SEM_SHOW
#define INCLUDE_POSIX_SIGNALS
#define INCLUDE_POSIX_TIMERS
#define INCLUDE_POSIX_TIMER_SHOW
#define INCLUDE_PROTECT_INTERRUPT_STACK
#define INCLUDE_PROTECT_TASK_STACK
#define INCLUDE_PROTECT_TEXT
#define INCLUDE_PROTECT_VEC_TABLE
#define INCLUDE_PTYDRV
#define INCLUDE_Q_FIFO
#define INCLUDE_Q_PRI_BMAP
#define INCLUDE_Q_PRI_DELTA
#define INCLUDE_Q_PRI_LIST
#define INCLUDE_RAWFS
#define INCLUDE_RBUFF
#define INCLUDE_RBUFF_SHOW
#define INCLUDE_REBOOT_HOOKS
#define INCLUDE_REMLIB
#define INCLUDE_REMLIB_SYSCTL
#define INCLUDE_RNG_BUF
#define INCLUDE_ROMFS
#define INCLUDE_RTP
#define INCLUDE_RTP_APPL_INIT_BOOTLINE
#define INCLUDE_RTP_ARCH
#define INCLUDE_RTP_DEBUG
#define INCLUDE_RTP_DEBUG_COMMAND
#define INCLUDE_RTP_HOOKS
#define INCLUDE_RTP_SHELL_C
#define INCLUDE_RTP_SHELL_CMD
#define INCLUDE_RTP_SHOW
#define INCLUDE_RTP_SHOW_SHELL_CMD
#define INCLUDE_SC_IOS
#define INCLUDE_SC_KERNEL
#define INCLUDE_SC_MMAN
#define INCLUDE_SC_POSIX
#define INCLUDE_SC_SD
#define INCLUDE_SC_SHL
#define INCLUDE_SC_SOCKLIB
#define INCLUDE_SC_SYSCTL
#define INCLUDE_SELECT
#define INCLUDE_SELECT_SUPPORT
#define INCLUDE_SEM_BINARY
#define INCLUDE_SEM_BINARY_CREATE
#define INCLUDE_SEM_COUNTING
#define INCLUDE_SEM_COUNTING_CREATE
#define INCLUDE_SEM_DELETE
#define INCLUDE_SEM_EVENTS
#define INCLUDE_SEM_EXCHANGE
#define INCLUDE_SEM_INFO
#define INCLUDE_SEM_LIB
#define INCLUDE_SEM_MUTEX
#define INCLUDE_SEM_MUTEX_CREATE
#define INCLUDE_SEM_OPEN
#define INCLUDE_SEM_SHOW
#define INCLUDE_SHARED_DATA
#define INCLUDE_SHARED_DATA_SHOW
#define INCLUDE_SHARED_DATA_SHOW_SHELL_CMD
#define INCLUDE_SHELL
#define INCLUDE_SHELL_BANNER
#define INCLUDE_SHELL_CORE
#define INCLUDE_SHELL_EMACS_MODE
#define INCLUDE_SHELL_INTERP_C
#define INCLUDE_SHELL_INTERP_CMD
#define INCLUDE_SHELL_VI_MODE
#define INCLUDE_SHL
#define INCLUDE_SHL_SHELL_CMD
#define INCLUDE_SHL_SHOW
#define INCLUDE_SHOW_ROUTINES
#define INCLUDE_SIGEVENT
#define INCLUDE_SIGNALS
#define INCLUDE_SIGNAL_ARCH
#define INCLUDE_SIO
#define INCLUDE_SLL
#define INCLUDE_SOCKLIB
#define INCLUDE_SPINLOCK
#define INCLUDE_SPY
#define INCLUDE_STARTUP_SCRIPT
#define INCLUDE_STAT_SYM_TBL
#define INCLUDE_STDIO
#define INCLUDE_STDIO_SHOW
#define INCLUDE_SV_DATACOLLECTOR
#define INCLUDE_SYM_SHELL_CMD
#define INCLUDE_SYM_TBL
#define INCLUDE_SYM_TBL_INIT
#define INCLUDE_SYM_TBL_SHOW
#define INCLUDE_SYSCALL_HOOKS
#define INCLUDE_SYSCLK_INIT
#define INCLUDE_SYSCTL
#define INCLUDE_SYSCTL_HW
#define INCLUDE_SYSDBG_FLAG
#define INCLUDE_SYSHW_INIT
#define INCLUDE_SYSHW_INIT2
#define INCLUDE_SYSHW_INIT_1
#define INCLUDE_SYS_START
#define INCLUDE_SYS_TIMESTAMP
#define INCLUDE_TASK_CREATE_DELETE
#define INCLUDE_TASK_CREATE_HOOKS
#define INCLUDE_TASK_HOOKS
#define INCLUDE_TASK_HOOKS_SHOW
#define INCLUDE_TASK_INFO
#define INCLUDE_TASK_LIST
#define INCLUDE_TASK_OPEN
#define INCLUDE_TASK_RESTART
#define INCLUDE_TASK_SHELL_CMD
#define INCLUDE_TASK_SHOW
#define INCLUDE_TASK_STACK_ALLOC
#define INCLUDE_TASK_STACK_NO_EXEC
#define INCLUDE_TASK_SWAP_HOOKS
#define INCLUDE_TASK_SWITCH_HOOKS
#define INCLUDE_TASK_VARS_TEST
#define INCLUDE_TIMER_OPEN
#define INCLUDE_TIMESTAMP
#define INCLUDE_TIMEX
#define INCLUDE_TIP
#define INCLUDE_TRIGGERING
#define INCLUDE_TRIGGER_SHOW
#define INCLUDE_TRIG_DATACOLLECTOR
#define INCLUDE_TTY_DEV
#define INCLUDE_TYLIB
#define INCLUDE_UNLOADER
#define INCLUDE_UNLOADER_SHELL_CMD
#define INCLUDE_USER_APPL
#define INCLUDE_USE_NATIVE_SHELL
#define INCLUDE_VIRTUAL_DISK
#define INCLUDE_VM_INVTBL
#define INCLUDE_VM_RTP
#define INCLUDE_VM_SHOW
#define INCLUDE_VM_SHOW_SHELL_CMD
#define INCLUDE_VXCPULIB
#define INCLUDE_VXDBG
#define INCLUDE_VXDBG_HOOK
#define INCLUDE_VXDBG_MODULE
#define INCLUDE_VXDBG_RUNCTRL
#define INCLUDE_VXEVENTS
#define INCLUDE_VXMEMPROBE_INIT
#define INCLUDE_VXMUX_MBLK
#define INCLUDE_VXMUX_NULLBUFPOOL
#define INCLUDE_VXSIM_IFCONFIG
#define INCLUDE_VX_TRADITIONAL_SCHEDULER
#define INCLUDE_WATCHDOGS
#define INCLUDE_WATCHDOGS_CREATE_DELETE
#define INCLUDE_WATCHDOGS_SHOW
#define INCLUDE_WB_RUNTIME_SUPPORT
#define INCLUDE_WDB
#define INCLUDE_WDB_ALWAYS_ENABLED
#define INCLUDE_WDB_BANNER
#define INCLUDE_WDB_BP
#define INCLUDE_WDB_BP_SYNC
#define INCLUDE_WDB_COMM_PIPE
#define INCLUDE_WDB_CTXT
#define INCLUDE_WDB_DIRECT_CALL
#define INCLUDE_WDB_DPRINTF
#define INCLUDE_WDB_EVENTPOINTS
#define INCLUDE_WDB_EVENTS
#define INCLUDE_WDB_EXC_NOTIFY
#define INCLUDE_WDB_EXIT_NOTIFY
#define INCLUDE_WDB_FUNC_CALL
#define INCLUDE_WDB_GOPHER
#define INCLUDE_WDB_MDL_SYM_SYNC
#define INCLUDE_WDB_MEM
#define INCLUDE_WDB_POST_KERNEL_INIT
#define INCLUDE_WDB_REG
#define INCLUDE_WDB_RTP
#define INCLUDE_WDB_RTP_BP
#define INCLUDE_WDB_RTP_CONTROL
#define INCLUDE_WDB_START_NOTIFY
#define INCLUDE_WDB_TASK
#define INCLUDE_WDB_TASK_BP
#define INCLUDE_WDB_TASK_COPROC_REG
#define INCLUDE_WDB_TASK_HOOKS
#define INCLUDE_WDB_TASK_REG
#define INCLUDE_WDB_TSFS
#define INCLUDE_WDB_USER_EVENT
#define INCLUDE_WDB_VIO
#define INCLUDE_WDB_VIO_LIB
#define INCLUDE_WINDVIEW
#define INCLUDE_WINDVIEW_CLASS
#define INCLUDE_WVUPLOAD_FILE
#define INCLUDE_WVUPLOAD_TSFSSOCK
#define INCLUDE_XBD
#undef INCLUDE_USER_RESERVED_MEMORY
#undef INCLUDE_PCI_PARAMS
#undef INCLUDE_VME_PARAMS
#undef INCLUDE_PCMCIA
#undef INCLUDE_SCSI
#undef INCLUDE_POWER_MGMT_CPU_BSP_SUPPORT
#undef INCLUDE_LPT
#undef INCLUDE_FD
#undef INCLUDE_IDE
#undef INCLUDE_ATA
#undef INCLUDE_SIO_POLL
#undef INCLUDE_PC_CONSOLE
#undef INCLUDE_AMP_CPU_01
#undef INCLUDE_AMP_CPU_00
#undef INCLUDE_LOCK_TEXT_SECTION
#undef INCLUDE_CPU_SLEEP_MODE_OFF
#undef INCLUDE_CPU_SLEEP_MODE_SHORT
#undef INCLUDE_CPU_SLEEP_MODE_LONG
#undef INCLUDE_AIM_MMU_MEM_POOL_CONFIG
#undef INCLUDE_AIM_MMU_CONFIG
#undef INCLUDE_AIM_MMU_PT_PROTECTION
#undef INCLUDE_MMU_OPTIMIZE
#undef INCLUDE_TYCODRV_5_2
#undef INCLUDE_SW_FP
#undef INCLUDE_CNS
#undef INCLUDE_HRFS
#undef INCLUDE_HRFS_READONLY
#undef INCLUDE_CDROMFS
#undef INCLUDE_XBD_TRANS
#undef INCLUDE_DOSFS
#undef INCLUDE_XBD_BLK_DEV
#undef INCLUDE_XBD_RAMDRV
#undef INCLUDE_XBD_PART_LIB
#undef INCLUDE_HRFS_DEFAULT_WRITE_MODE
#undef INCLUDE_HRFS_HISPEED_WRITE_MODE
#undef INCLUDE_HRFS_ACCESS_TIMESTAMP
#undef INCLUDE_HRFS_FORMAT
#undef INCLUDE_HRFS_CHKDSK
#undef INCLUDE_SSI
#undef INCLUDE_TLS_LOADER_SUPPORT
#undef INCLUDE_DIAB_INTRINSICS
#undef INCLUDE_ICC_INTRINSICS
#undef INCLUDE_NO_INTRINSICS
#undef INCLUDE_CPLUS_IOSTREAMS
#undef INCLUDE_POSIX_ADVISORY_FILE_LOCKING
#undef INCLUDE_DATACOLLECTOR_SHOW
#undef INCLUDE_ATA_SHOW
#undef INCLUDE_PCI_CFGSHOW
#undef INCLUDE_ISR_SHOW
#undef INCLUDE_POOL_SHOW
#undef INCLUDE_SIMPLE_BANNER
#undef INCLUDE_ISR_OBJECTS
#undef INCLUDE_SEM_READ_WRITE
#undef INCLUDE_SEM_READ_WRITE_CREATE
#undef INCLUDE_TASK_ROTATE
#undef INCLUDE_TASK_UTIL
#undef INCLUDE_TLS
#undef INCLUDE_ISR_DEFER
#undef INCLUDE_VXBUS
#undef INCLUDE_MEM_ALLOT
#undef INCLUDE_PX_SCHED_DEF_POLICIES
#undef INCLUDE_POSIX_PTHREAD_SCHEDULER
#undef INCLUDE_PX_SCHED_SPORADIC_POLICY
#undef INCLUDE_CUSTOM_SCHEDULER
#undef INCLUDE_VX_NATIVE_SCHEDULER
#undef INCLUDE_RAM_DISK
#undef INCLUDE_RAMDRV
#undef INCLUDE_MEMDRV
#undef INCLUDE_VRFS
#undef INCLUDE_UTF
#undef INCLUDE_STRING_SEARCH
#undef INCLUDE_WVNETD
#undef INCLUDE_WVUPLOAD_SOCK
#undef INCLUDE_USER_TIMESTAMP
#undef INCLUDE_SEQ_TIMESTAMP
#undef INCLUDE_WV_BUFF_USER
#undef INCLUDE_POSIX_TRACE
#undef INCLUDE_POSIX_TRACE_TIMESTAMP
#undef INCLUDE_SLL_CREATE_DELETE
#undef INCLUDE_DLL_CREATE_DELETE
#undef INCLUDE_AVL_TREES
#undef INCLUDE_SYSCTL_CLI
#undef INCLUDE_WVTIPC
#undef INCLUDE_SM_OBJ
#undef INCLUDE_DOSFS_MAIN
#undef INCLUDE_DOSFS_CACHE
#undef INCLUDE_DOSFS_SHOW
#undef INCLUDE_SCSI_DOSFS
#undef INCLUDE_VXBUS_DISK
#undef INCLUDE_CACHE_COMPACT_DMA_SUPPORT
#undef INCLUDE_CORE_DUMP
#undef INCLUDE_CORE_DUMP_RTP
#undef INCLUDE_POSIX_SHM
#undef INCLUDE_POSIX_SHM_API
#undef INCLUDE_DEVMEM
#undef INCLUDE_AF_MIPC_SOCKETS
#undef INCLUDE_DSI_DYNAMIC_INIT
#undef INCLUDE_DSI_STATIC_INIT
#undef INCLUDE_USB_HOST_CLASS_INIT
#undef INCLUDE_SPINLOCK_ISR_ND
#undef INCLUDE_SPINLOCK_ND_TIMED
#undef INCLUDE_DEBUG_KPRINTF
#undef INCLUDE_DEBUG_KPUTS
#undef INCLUDE_DEBUG_KWRITE_SIO
#undef INCLUDE_DEBUG_KWRITE_USER
#undef INCLUDE_WDB_COMM_SERIAL
#undef INCLUDE_WDB_COMM_NETWORK
#undef INCLUDE_WDB_COMM_VTMD
#undef INCLUDE_WDB_COMM_TIPC
#undef INCLUDE_WDB_COMM_MIPC
#undef INCLUDE_WDB_COMM_CUSTOM
#undef INCLUDE_NET_INIT_SKIP
#undef INCLUDE_TIPC
#undef INCLUDE_MIPC_SM
#undef INCLUDE_WDB_DWARF_EXPR_TEST
#undef INCLUDE_WDB_PRE_KERNEL_INIT
#undef INCLUDE_RTP_APPL_USER
#undef INCLUDE_RTP_POSIX_PSE52
#undef INCLUDE_POSIX_THREAD_CPUTIME
#undef INCLUDE_STANDALONE_SYM_TBL
#undef INCLUDE_SHELL_HISTORY_FILE
#undef INCLUDE_NET_SYM_TBL
#undef INCLUDE_NFS2_CLIENT
#undef INCLUDE_CORE_NFS_CLIENT
#undef INCLUDE_NFS3_CLIENT
#undef INCLUDE_NFS_CLIENT_ALL
#undef INCLUDE_RPC
#undef INCLUDE_NFS_MOUNT_ALL
#undef INCLUDE_NFS2_SERVER
#undef INCLUDE_CORE_NFS_SERVER
#undef INCLUDE_NFS_SERVER_INSTALL
#undef INCLUDE_NFS3_SERVER
#undef INCLUDE_NFS_SERVER_ALL
#undef INCLUDE_ETHERNET
#undef INCLUDE_GTF
#undef INCLUDE_GTF_TIMER_START
#undef INCLUDE_INETLIB
#undef INCLUDE_IPATTACH
#undef INCLUDE_MIB2_IF
#undef INCLUDE_NET_POOL
#undef INCLUDE_TFTP_CLIENT
#undef INCLUDE_XDR
#undef INCLUDE_GETSERVBYNAME
#undef INCLUDE_ARP_API
#undef INCLUDE_IPDHCPC
#undef INCLUDE_GETADDRINFO
#undef INCLUDE_GETNAMEINFO
#undef INCLUDE_GETNETBYNAME
#undef INCLUDE_IFCONFIG
#undef INCLUDE_NETSTAT
#undef INCLUDE_ROUTECMD
#undef INCLUDE_SECURITY
#undef INCLUDE_RTP_APPL_INIT_STRING
#undef INCLUDE_RTP_APPL_INIT_CMD_SHELL_SCRIPT
#undef INCLUDE_SM_COMMON
#undef INCLUDE_SM_AND_DSHM
#undef INCLUDE_SM_AND_MIPC
#undef INCLUDE_SM_NET
#undef INCLUDE_SM_NET_SHOW
#undef INCLUDE_SMEND
#undef INCLUDE_VXTESTV2
#undef INCLUDE_VXTESTV2_LF_DRIVER
#undef INCLUDE_VXTESTV2_SF_DRIVER
#undef INCLUDE_VXTESTV2_SF_DRIVER_CALLS
#undef INCLUDE_VXTESTV2_WDB
#undef INCLUDE_VXTESTV2_SHELL
#undef INCLUDE_VXTESTV2_SCALE
#undef INCLUDE_VXTESTV2_EMBEDDED
#undef INCLUDE_VXTESTV2_AUTORUN
#undef INCLUDE_VXTESTV2_SYSPARAMS
#undef INCLUDE_VXTESTV2_POSIX_FS
#undef INCLUDE_TM_CPCLIB
#undef INCLUDE_TM_SPINLOCKLIB
#undef INCLUDE_TM_SPINLOCK_ISR_ND_LIB
#undef INCLUDE_TM_VXATOMICLIB
#undef INCLUDE_TM_CACHELIB
#undef INCLUDE_TM_CACHELIB_MALLOC
#undef INCLUDE_TM_INTARCHLIB
#undef INCLUDE_TM_TASKLIB
#undef INCLUDE_TM_ADRSPACELIB
#undef INCLUDE_TM_DBGLIB
#undef INCLUDE_TM_ISRLIB
#undef INCLUDE_TM_KERNELLIB
#undef INCLUDE_TM_SEMBLIB
#undef INCLUDE_TM_SEMCLIB
#undef INCLUDE_TM_SEMLIBINLINE
#undef INCLUDE_TM_SEMMLIB
#undef INCLUDE_TM_SEMRWLIB
#undef INCLUDE_TM_SYSCALLLIB
#undef INCLUDE_TM_TASKCREATELIB
#undef INCLUDE_TM_TASKHOOKLIB
#undef INCLUDE_TM_TASKRESTARTLIB
#undef INCLUDE_TM_VMTEST
#undef INCLUDE_TM_VXCPULIB
#undef INCLUDE_TM_MIPSDSMLIB
#undef INCLUDE_TM_BSPAPI
#undef INCLUDE_TM_MODEL
#undef INCLUDE_TM_SYSCLOCK
#undef INCLUDE_TM_AUXCLOCK
#undef INCLUDE_TM_NVRAM
#undef INCLUDE_TM_TIMESTAMP
#undef INCLUDE_TM_BOOT_APP
#undef INCLUDE_BOOT_TEST_FUNCS
#undef INCLUDE_BOOT_RAM_IMAGE
#undef INCLUDE_TM_FFSLIB
#undef INCLUDE_TM_FSINITTESTS
#undef INCLUDE_TM_FSTESTS
#undef INCLUDE_TM_ATADRV
#undef INCLUDE_TM_IOBASICLIB
#undef INCLUDE_TM_LOGINLIB
#undef INCLUDE_TM_ENVLIB
#undef INCLUDE_TM_HASHLIB
#undef INCLUDE_TM_ANSICTYPE
#undef INCLUDE_TM_ANSISETJMP
#undef INCLUDE_TM_ANSISTDARG
#undef INCLUDE_TM_ANSISTDLIB
#undef INCLUDE_TM_BLIB
#undef INCLUDE_TM_CLOCKLIB
#undef INCLUDE_TM_MEMLIB
#undef INCLUDE_TM_MEMDRVLIB
#undef INCLUDE_TM_MSGQLIB
#undef INCLUDE_TM_SEMSHOW
#undef INCLUDE_TM_SIGLIB
#undef INCLUDE_TM_SYMLIB
#undef INCLUDE_TM_PGPOOLPHYSLIB
#undef INCLUDE_TM_PGPOOLVIRTLIB
#undef INCLUDE_TM_MQPXLIB
#undef INCLUDE_TM_NETBUFLIB
#undef INCLUDE_TM_OBJLIB
#undef INCLUDE_TM_PGMGRLIB
#undef INCLUDE_TM_PRIINHERIT
#undef INCLUDE_TM_SALLIB
#undef INCLUDE_SAL_COMMON
#undef INCLUDE_TM_SALSTRESSLIB
#undef INCLUDE_TM_TASKOPEN
#undef INCLUDE_TM_MEMPARTLIB
#undef INCLUDE_TM_POOLLIB
#undef INCLUDE_TM_PXTRACEEVENTID
#undef INCLUDE_TM_HOOKLIB
#undef INCLUDE_TM_WORKQLIB
#undef INCLUDE_TM_WDCREATELIB
#undef INCLUDE_TM_ANSITIME
#undef INCLUDE_TM_TASKSHOW
#undef INCLUDE_TM_PIPEDRV
#undef INCLUDE_TM_PIPEDRV2
#undef INCLUDE_TM_TASKVARLIB
#undef INCLUDE_TM_PMLIB
#undef INCLUDE_TM_TASKINFO
#undef INCLUDE_TM_SOCKLIB
#undef INCLUDE_TM_MEMPARTFUNC
#undef INCLUDE_TM_PTHREADLIB
#undef INCLUDE_TM_SHMLIB
#undef INCLUDE_TM_WINDSTRESSTEST
#undef INCLUDE_TM_HEAPSTRESSTEST
#undef INCLUDE_TM_WINDKERNELLIB
#undef INCLUDE_TM_MACROTEST
#undef INCLUDE_TM_PINGLIB
#undef INCLUDE_PING
#undef INCLUDE_TM_ERRNOLIB_SMP
#undef INCLUDE_TM_COMPS
#undef INCLUDE_TM_USBSHOW
#undef INCLUDE_USB
#undef INCLUDE_USB_INIT
#undef INCLUDE_USB_MS_BULKONLY
#undef INCLUDE_USB_MS_BULKONLY_INIT
#undef INCLUDE_UHCI
#undef INCLUDE_TM_VXBTEST
#undef INCLUDE_VXBUS_SHOW
#undef INCLUDE_TM_VXBPCIACCESS
#undef INCLUDE_PCI_BUS
#undef INCLUDE_TM_VXBVIRTACCESS
#undef INCLUDE_TM_VXBPARAMSYS
#undef INCLUDE_PARAM_SYS
#undef INCLUDE_TM_VXBTESTDMABUFFER
#undef INCLUDE_DMA_SYS
#undef INCLUDE_TM_VXBTESTDMALIB
#undef INCLUDE_TM_VXBTIMERLIB
#undef INCLUDE_TIMER_SYS
#undef INCLUDE_TM_VXBTESTSIO
#undef INCLUDE_SIO_UTILS
#undef INCLUDE_TM_VXBTIMERDRIVER
#undef INCLUDE_WDB_PROXY
#undef INCLUDE_WDB_PROXY_UDP
#undef INCLUDE_WDB_PROXY_TIPC
#undef INCLUDE_WDB_PROXY_MIPC
#undef INCLUDE_SAL_CLIENT
#undef INCLUDE_SAL_SERVER
#undef INCLUDE_SNS_SHOW
#undef INCLUDE_UN_COMP
#undef INCLUDE_SNS
#undef INCLUDE_SNS_RTP
#undef INCLUDE_SNS_MP
#undef INCLUDE_SNS_MP_RTP
#undef INCLUDE_SNS_COMMON
#undef INCLUDE_SNS_RTP_HOOK
#undef INCLUDE_UN
#undef INCLUDE_DSI_SOCKET
#undef INCLUDE_DSI_POOL
#undef INCLUDE_UN_SHOW
#undef INCLUDE_UN_COMP_SHOW
#undef INCLUDE_CORE_DUMP_SHOW
#undef INCLUDE_CORE_DUMP_MEM_FILTER
#undef INCLUDE_CORE_DUMP_MEM_POOL
#undef INCLUDE_CORE_DUMP_COMPRESS
#undef INCLUDE_CORE_DUMP_COMPRESS_RLE
#undef INCLUDE_CORE_DUMP_COMMON_COMPRESS_ZLIB
#undef INCLUDE_CORE_DUMP_COMMON_COMPRESS_RLE
#undef INCLUDE_CORE_DUMP_UTIL
#undef INCLUDE_CORE_DUMP_MEM
#undef INCLUDE_CORE_DUMP_RAW_DEV
#undef INCLUDE_CORE_DUMP_RTP_COMPRESS_ZLIB
#undef INCLUDE_CORE_DUMP_RTP_COMPRESS_RLE
#undef INCLUDE_CORE_DUMP_RTP_FS
#undef INCLUDE_MEM_EDR
#undef INCLUDE_MEM_EDR2
#undef INCLUDE_MEM_EDR_RTC
#undef INCLUDE_MEM_EDR_SHOW
#undef INCLUDE_MEM_EDR_RTP_SHOW
#undef INCLUDE_CACHE_DMA32_LIB
#undef INCLUDE_MAPPED_FILES_SHOW
#undef INCLUDE_MAPPED_FILES_SHOW_SHELL_CMD
#undef INCLUDE_MEM_EDR_SHELL_CMD
#undef INCLUDE_MEM_EDR_RTP_SHELL_CMD
#undef INCLUDE_HISTORY_FILE_SHELL_CMD
#undef INCLUDE_CAN_NETWORK_INIT
#undef INCLUDE_WNCAN_SHOW
#undef INCLUDE_WNCAN_DEVIO
#undef INCLUDE_ESD_CAN_PCI_200
#undef INCLUDE_PPC5XX_WNCAN
#undef INCLUDE_MCF5282_WNCAN
#undef INCLUDE_ESD_CAN_PCI_200_2
#undef INCLUDE_ESD_CAN_PC104_200
#undef INCLUDE_MSMCAN_PC104
#undef INCLUDE_MPC5200_WNCAN
#undef INCLUDE_TOLAPAI_CAN
#undef INCLUDE_MPC5121E_WNCAN
#undef INCLUDE_DOSFS_FAT
#undef INCLUDE_DOSFS_FMT
#undef INCLUDE_DOSFS_CHKDSK
#undef INCLUDE_TAR
#undef INCLUDE_DOSFS_PRTMSG_LEVEL
#undef INCLUDE_DOSFS_VOL_BIO_BUFFER_SIZE
#undef INCLUDE_DOSFS_DIR_VFAT
#undef INCLUDE_DOSFS_DIR_FIXED
#undef INCLUDE_DOWNLOADABLE_DRIVERS
#undef INCLUDE_PLB_BUS
#undef INCLUDE_VXIPI
#undef INCLUDE_INTCTLR_LIB
#undef INCLUDE_NON_VOLATILE_RAM
#undef INCLUDE_VXBUS_INIT
#undef INCLUDE_VXBUS_ACTIVATE
#undef INCLUDE_VXB_SYS_CLK
#undef INCLUDE_VXB_AUX_CLK
#undef INCLUDE_VXB_TIMESTAMP
#undef INCLUDE_TIMER_SYS_DELAY
#undef INCLUDE_TIMER_STUB
#undef INCLUDE_VXBUS_DEV_INIT
#undef INCLUDE_VXBUS_DEVICE_CONNECT
#undef INCLUDE_TIMER_SYS_SHOW
#undef VXBUS_TABLE_CONFIG
#undef INCLUDE_PCI_BUS_AUTOCONF
#undef INCLUDE_PCI_OLD_CONFIG_ROUTINES
#undef INCLUDE_PCI_BUS_SHOW
#undef INCLUDE_VXBUS_SM_SUPPORT
#undef INCLUDE_WRLOAD
#undef INCLUDE_WRLOAD_IMAGE_BUILD
#undef INCLUDE_RAPIDIO_BUS
#undef RAPIDIO_BUS_AUTOCONFIG
#undef RAPIDIO_BUS_STATIC_PROBE
#undef RAPIDIO_BUS_STATIC_TABLE
#undef INCLUDE_VXB_LEGACY_INTERRUPTS
#undef INCLUDE_BOOT_APP
#undef INCLUDE_BOOT_EXC_HANDLER
#undef INCLUDE_BOOT_INIT
#undef INCLUDE_BOOT_DELAYED_INIT
#undef INCLUDE_BOOT_MMU_BASIC
#undef INCLUDE_BOOT_ELF
#undef INCLUDE_ELF_MEMORY_MAP
#undef INCLUDE_BOOT_SHELL
#undef INCLUDE_BOOT_MEM_CMDS
#undef INCLUDE_BOOT_EDR_SUPPORT
#undef INCLUDE_BOOT_NETWORK
#undef INCLUDE_NET_BOOT_CONFIG
#undef INCLUDE_BOOT_NET_DEVICES
#undef INCLUDE_BOOT_FTP_LOADER
#undef INCLUDE_BOOT_TFTP_LOADER
#undef INCLUDE_BOOT_RSH_LOADER
#undef INCLUDE_BOOT_END
#undef INCLUDE_BOOT_VXBUS
#undef INCLUDE_BOOT_ETH_MAC_HANDLER
#undef INCLUDE_BOOT_ETH_ADR_SET
#undef INCLUDE_BOOT_DHCPC
#undef INCLUDE_BOOT_FILESYSTEMS
#undef INCLUDE_BOOT_FS_DEVICES
#undef INCLUDE_BOOT_FD_LOADER
#undef INCLUDE_BOOT_USB_FS_LOADER
#undef INCLUDE_BOOT_USB_SHOW
#undef INCLUDE_USB_SHOW
#undef INCLUDE_BOOT_TSFS_LOADER
#undef INCLUDE_TSFS_BOOT_VIO_CONSOLE
#undef INCLUDE_DSHM
#undef INCLUDE_DSHM_MUX
#undef INCLUDE_DSHM_ADAPT
#undef INCLUDE_DSHM_DEBUG
#undef INCLUDE_DSHM_SVC_MNG
#undef INCLUDE_DSHM_MSG_SM
#undef INCLUDE_DSHM_NOWRING
#undef INCLUDE_DSHM_BUS
#undef INCLUDE_DSHM_BUS_PLB
#undef INCLUDE_DSHM_VXPLB
#undef INCLUDE_DSHM_MEM
#undef INCLUDE_DSHM_RW_LOCK
#undef INCLUDE_DSHM_OWRING
#undef INCLUDE_DSHM_SPINLOCK
#undef INCLUDE_DSHM_POW2
#undef INCLUDE_MFS
#undef INCLUDE_MFS_CLIENT
#undef INCLUDE_MFS_SERVER
#undef INCLUDE_MFS_SERVER_FD_CACHE
#undef INCLUDE_MIPC_UNSUPPORTED
#undef INCLUDE_MIPC_SHOW
#undef INCLUDE_MIPC_DEMO
#undef INCLUDE_AF_MIPC_DEMO
#undef INCLUDE_MND
#undef INCLUDE_MSD
#undef INCLUDE_TIPC_SHOW
#undef INCLUDE_CONFIG_TIPC_SOCKET_API
#undef INCLUDE_TIPC_MEMPOOL
#undef INCLUDE_TIPC_DEFINES
#undef INCLUDE_TIPC_NODEBUG
#undef INCLUDE_TIPC_NOSYS_MSGS
#undef INCLUDE_TIPC_NOCFG_SERVICE
#undef INCLUDE_TIPC_NOSOCKET
#undef INCLUDE_USE_LIBTIPC
#undef INCLUDE_BUILD_TIPC_SRC
#undef INCLUDE_TIPC_CONFIG_STR
#undef INCLUDE_TIPC_CONFIG_HOOK_BOOT
#undef INCLUDE_TIPC_CONFIG_HOOK_USER
#undef INCLUDE_TIPC_MEDIA_ETH
#undef INCLUDE_TIPC_IP
#undef INCLUDE_TIPC_ONLY
#undef INCLUDE_TIPC_TS
#undef INCLUDE_TIPC_IS
#undef INCLUDE_VXBUS_END_QCTRL
#undef DRV_RESOURCE_FSLGPIO
#undef DRV_RESOURCE_QORIQQMAN
#undef DRV_TIMER_MIPSR4K
#undef DRV_TIMER_SB1
#undef DRV_TIMER_CN3XXX
#undef INCLUDE_XLR_TIMER
#undef DRV_TIMER_OPENPIC
#undef DRV_RESOURCE_QORIQBMAN
#undef DRV_RESOURCE_QORIQLAW
#undef DRV_RESOURCE_QORIQFMAN
#undef DRV_RESOURCE_QORIQFMAN_SOFTPARSE_ASSEMBLER
#undef DRV_RESOURCE_QORIQFMAN_SOFTPARSE
#undef DRV_PCIBUS_QORIQ_PCIEX
#undef INCLUDE_AN983_VXB_END
#undef INCLUDE_GENERICPHY
#undef INCLUDE_VXB_CPM
#undef INCLUDE_TC3C905_VXB_END
#undef INCLUDE_NE2000_VXB_END
#undef INCLUDE_MOT_ETSEC_HEND
#undef INCLUDE_FCC_VXB_END
#undef INCLUDE_MII_BUS
#undef INCLUDE_MDIO
#undef INCLUDE_BCM52XXPHY
#undef INCLUDE_MOT_FEC_HEND
#undef INCLUDE_FEC_VXB_END
#undef INCLUDE_FEI8255X_VXB_END
#undef INCLUDE_GT64120A_MF
#undef INCLUDE_GT64120A_PCI
#undef INCLUDE_GT64120A_DMA
#undef INCLUDE_GT64120A_TIMER
#undef INCLUDE_GT64120A_INTCTLR
#undef INCLUDE_GT64120A_SDRAM
#undef INCLUDE_GT64120A_I2O
#undef INCLUDE_GEI_HEND
#undef INCLUDE_GEI825XX_VXB_END
#undef INCLUDE_GEI825XX_VXB_END2
#undef INCLUDE_END2
#undef INCLUDE_HEND_PARAM_SYS
#undef INCLUDE_HEND_NPT
#undef DRV_I8259VXBPIC
#undef DRV_TIMER_IXP400
#undef DRV_PCIBUS_IXP4XX
#undef INCLUDE_VXB_DMA_END2_IXP4XX_PCI
#undef INCLUDE_AM79C97X_VXB_END
#undef DRV_PCIBUS_M83XX
#undef DRV_PCIBUS_M83XX_EX
#undef DRV_RESOURCE_M85XXCCSR
#undef INCLUDE_M85XX_CPU
#undef DRV_PCIBUS_M85XX
#undef INCLUDE_M85XX_RAPIDIO
#undef INCLUDE_M85XX_RIO_SM_CFG
#undef INCLUDE_GENERICTBIPHY
#undef INCLUDE_BCM54XXPHY
#undef INCLUDE_DM9161PHY
#undef INCLUDE_GEITBIPHY
#undef INCLUDE_ICP175CPHY
#undef INCLUDE_LXT972PHY
#undef INCLUDE_MV88E1X11PHY
#undef INCLUDE_MV88E1113PHY
#undef INCLUDE_RTL8201PHY
#undef INCLUDE_RTL8169PHY
#undef INCLUDE_VSC82XXPHY
#undef DRV_MII_DTSEC_MDIO
#undef DRV_MII_TGEC_MDIO
#undef INCLUDE_RMI_MDIO
#undef INCLUDE_TSEC_MDIO
#undef INCLUDE_UCC_MDIO
#undef DRV_MII_DTEPHY
#undef INCLUDE_DUMMY_MDIO
#undef INCLUDE_NS83902_VXB_END
#undef INCLUDE_NS8381X_VXB_END
#undef DRV_KBD_I8042
#undef DRV_VGA_M6845
#undef DRV_TIMER_DEC_PPC
#undef INCLUDE_QE_FCC_HEND
#undef INCLUDE_QUICC_ENGINE_UTILS
#undef INCLUDE_RTL8169_VXB_END
#undef INCLUDE_RTL8139_VXB_END
#undef INCLUDE_SBE_VXB_END
#undef INCLUDE_SCC_VXB_END
#undef INCLUDE_MOT_TSEC_HEND
#undef INCLUDE_TSEC_VXB_END
#undef INCLUDE_TSEC_VXB_END2
#undef DRV_SIO_NS16550
#undef DRV_SIO_COLDFIRE
#undef DRV_SIO_IXP400
#undef DRV_SIO_SB1
#undef DRV_SIO_PRIMECELL
#undef DRV_SIO_OCTEON
#undef DRV_SIO_M5XXX_PSC
#undef DRV_SIO_IMX
#undef DRV_SIO_DAVINCI
#undef DRV_SIO_AT91
#undef INCLUDE_OHCI
#undef INCLUDE_EHCI
#undef INCLUDE_MHCI
#undef INCLUDE_SYNOPSYSHCI
#undef INCLUDE_USBTOOL
#undef INCLUDE_USB_TRACK_EHCD
#undef INCLUDE_USB_TRACK_UHCD
#undef INCLUDE_USB_TRACK_OHCD
#undef INCLUDE_USB_TRACK_MHCD
#undef INCLUDE_USB_TRACK_SYNOPSYSHCD
#undef INCLUDE_USB_TRACK_TU
#undef INCLUDE_USB_TRACK_USBD
#undef INCLUDE_USB_TRACK_HUB
#undef INCLUDE_USB_TRACK_GEN1_SPK
#undef INCLUDE_USB_TRACK_GEN1_BLK
#undef INCLUDE_USB_TRACK_GEN1_CBI
#undef INCLUDE_USB_TRACK_GEN1_MSE
#undef INCLUDE_USB_TRACK_GEN1_KBD
#undef INCLUDE_USB_TRACK_GEN1_PRN
#undef INCLUDE_USB_TRACK_GEN1_END
#undef INCLUDE_USB_TRACK_GEN2_HLP
#undef INCLUDE_USB_TRACK_GEN2_MSC
#undef INCLUDE_USB_TRACK_GEN2_MSE
#undef INCLUDE_USB_TRACK_GEN2_KBD
#undef INCLUDE_USB_TRACK_GEN2_PRN
#undef INCLUDE_USB_TRACK_GEN2_END
#undef INCLUDE_USB_TRACK_GEN2_SER
#undef INCLUDE_USB_SPEAKER
#undef INCLUDE_USB_MS_CBI
#undef INCLUDE_USB_MOUSE
#undef INCLUDE_USB_KEYBOARD
#undef INCLUDE_USB_PRINTER
#undef INCLUDE_USB_PEGASUS_END
#undef INCLUDE_USB_GEN2_HELPER
#undef INCLUDE_USB_GEN2_STORAGE
#undef INCLUDE_USB_GEN2_MOUSE
#undef INCLUDE_USB_GEN2_KEYBOARD
#undef INCLUDE_USB_GEN2_PRINTER
#undef INCLUDE_USB_GEN2_PEGASUS
#undef INCLUDE_USB_GEN2_SER_FTDI232
#undef INCLUDE_PDIUSBD12
#undef INCLUDE_PHILIPS1582
#undef INCLUDE_NET2280
#undef INCLUDE_FSL_TCD
#undef INCLUDE_USB_TARG
#undef INCLUDE_KBD_EMULATOR
#undef INCLUDE_PRN_EMULATOR
#undef INCLUDE_D12_EMULATOR
#undef INCLUDE_MS_EMULATOR
#undef INCLUDE_SER_EMULATOR
#undef INCLUDE_KBD_EMULATOR_INIT
#undef INCLUDE_PRN_EMULATOR_INIT
#undef INCLUDE_MS_EMULATOR_INIT
#undef INCLUDE_SER_EMULATOR_INIT
#undef INCLUDE_HCD_BUS
#undef INCLUDE_USB_MOUSE_INIT
#undef INCLUDE_USB_PRINTER_INIT
#undef INCLUDE_USB_SPEAKER_INIT
#undef INCLUDE_USB_MS_CBI_INIT
#undef INCLUDE_USB_PEGASUS_END_INIT
#undef INCLUDE_USB_AUDIO_DEMO
#undef INCLUDE_USB_HEADSET_DEMO
#undef INCLUDE_USB_GEN2_PRINTER_INIT
#undef INCLUDE_USB_GEN2_END_INIT
#undef INCLUDE_USB_GEN2_MOUSE_INIT
#undef INCLUDE_USB_GEN2_STORAGE_INIT
#undef INCLUDE_UHCI_INIT
#undef INCLUDE_OHCI_INIT
#undef INCLUDE_EHCI_INIT
#undef INCLUDE_SYNOPSYSHCI_INIT
#undef INCLUDE_MHCI_INIT
#undef INCLUDE_USB_KEYBOARD_INIT
#undef INCLUDE_USB_GEN2_KEYBOARD_INIT
#undef INCLUDE_USB_GEN2_KEYBOARD_SHELL_ATTACH
#undef INCLUDE_USB_GEN2_KEYBOARD_BOOTSHELL_ATTACH
#undef INCLUDE_USB_GEN2_DM960X
#undef INCLUDE_USB_GEN2_ASIX
#undef INCLUDE_USB_GEN2_SERIAL_INIT
#undef INCLUDE_USB_GEN2_SERIAL_PCCONSOLE_INIT
#undef INCLUDE_USB_GEN2_SER_WRS_CDC
#undef INCLUDE_USB_KEYBOARD_SHELL_ATTACH
#undef INCLUDE_USB_KEYBOARD_BOOTSHELL_ATTACH
#undef DRV_INTCTLR_ADS5121E_CPLD
#undef DRV_INTCTLR_ALTERA
#undef DRV_SIO_ALTERA_JTAG
#undef DRV_TIMER_ALTERA
#undef DRV_VXBEND_ALTERA_TSE
#undef DRV_SIO_ALTERA_UART
#undef DRV_TIMER_AMBA
#undef DRV_PCIBUS_ARMAXI
#undef DRV_ARM_GIC
#undef DRV_VXBEND_AT91EMAC
#undef DRV_INTCTLR_AT91
#undef DRV_TIMER_AT91
#undef DRV_VXBEND_COMCERTO_GEMAC
#undef DRV_INTCTLR_COMCERTO
#undef DRV_PCIBUS_COMCERTO
#undef DRV_TIMER_COMCERTO
#undef DRV_INTCTLR_DAVINCI
#undef DRV_TIMER_DAVINCI
#undef DRV_VXBEND_DC2114X
#undef DRV_VXBEND_DM9000A
#undef DRV_VXBEND_DTSEC
#undef DRV_EB_GIC
#undef DRV_INTCTLR_EPIC
#undef INCLUDE_ETSEC_VXB_END
#undef INCLUDE_ETSEC_VXB_END2
#undef DRV_NVRAM_FILE
#undef DRV_FW_FSL_AXE
#undef DRV_DMA_FSL
#undef DRV_STORAGE_FSLSATA
#undef DRV_STORAGE_FSL_SDHC
#undef DRV_TIMER_I8253
#undef DRV_INTCTLR_I8259
#undef INCLUDE_IPIIX4_MF
#undef INCLUDE_EMAC_VXB_END
#undef INCLUDE_VXB_IBM_MAL
#undef INCLUDE_VXB_IBM_ZMII
#undef INCLUDE_VXB_IBM_RGMII
#undef INCLUDE_VXB_IBM_TAH
#undef DRV_TIMER_IMX31EPIT
#undef DRV_TIMER_IMX31GPT
#undef DRV_INTCTLR_IMX31
#undef DRV_INTCTLR_IMX51
#undef INCLUDE_INTCTLR_SHOW
#undef INCLUDE_INTCTLR_DYNAMIC_LIB
#undef INCLUDE_DRV_STORAGE_INTEL_AHCI
#undef INCLUDE_DRV_STORAGE_INTEL_AHCI_SHOW
#undef DRV_DMA_INTEL_EDMA
#undef DRV_MII_INTEL_GCU
#undef INCLUDE_DRV_STORAGE_INTEL_ICH
#undef INCLUDE_DRV_STORAGE_INTEL_ICH_SHOW
#undef DRV_TIMER_IA_TIMESTAMP
#undef DRV_INTCTLR_IOAPIC
#undef DRV_PCI_VIRTUAL
#undef DRV_INTCTLR_LOAPIC
#undef DRV_TIMER_LOAPIC
#undef DRV_VXBEND_LPC24XXEMAC
#undef DRV_INTCTL_LPC24XX
#undef DRV_TIMER_LPC24XX
#undef DRV_DMA_M512X
#undef INCLUDE_M512XFEC_VXB_END
#undef DRV_MF_M512X_FIFOC
#undef DRV_TIMER_M5XXX_GPT
#undef DRV_TIMER_M85XX
#undef DRV_TIMER_MC146818
#undef DRV_INTCTLR_MIPS
#undef DRV_INTCTLR_MIPS_SBE
#undef DRV_INTCTLR_MIPS_CAV
#undef DRV_INTCTLR_MIPS_XLR
#undef DRV_INTCTLR_MIPS_MT_IPI
#undef DRV_INTCTLR_MPAPIC
#undef INCLUDE_MSC01_PCI
#undef DRV_VXBEND_MYRILANAI
#undef INCLUDE_OCTEON_VXB_END
#undef DRV_VXBEND_OCTEON_MGMT
#undef INCLUDE_OCTEON_RGMII
#undef INCLUDE_OCTEON_MDIO
#undef INCLUDE_OCTEON_SGMII
#undef INCLUDE_OCTEON_SPI4000
#undef INCLUDE_SPI4000_MDIO
#undef INCLUDE_SPI4000_PHY
#undef DRV_PCIBUS_OCTEON
#undef DRV_PCIBUS_OCTEON_PCIEX
#undef DRV_INTCTLR_OMAP2530
#undef DRV_TIMER_OMAP2530
#undef DRV_DMA_OMAP35XX
#undef DRV_INTCTLR_OMAP35XX
#undef DRV_STORAGE_OMAP35XX_MMCHS
#undef DRV_TIMER_OMAP35XX
#undef DRV_INTCTLR_OMAPL137
#undef DRV_TIMER_PPC405
#undef DRV_TIMER_PPC440
#undef INCLUDE_PPC440GX_PCI
#undef DRV_PCIBUS_PPC4XX_PCI
#undef DRV_PCIBUS_PPC4XX_PCIEX
#undef DRV_INTCTLR_UIC
#undef DRV_TIMER_QUICC_PPC
#undef DRV_INTCTLR_PXA3XXGPIO
#undef DRV_INTCTLR_PXA3XX
#undef DRV_TIMER_PXA3XX
#undef DRV_INTCTLR_QE
#undef DRV_INTCTLR_QUICC
#undef INCLUDE_XLR_GMAC_VXB_END
#undef DRV_VXBEND_XLRSPI4
#undef DRV_VXBEND_XLRXGMAC
#undef DRV_RESOURCE_XLRCPLD
#undef DRV_STORAGE_SI31XX
#undef DRV_SUPERIO_SMCFDC37X
#undef INCLUDE_SMSCLAN9118_VXB_END
#undef INCLUDE_SMSCLAN91C111_VXB_END
#undef DRV_VXBEND_TEI82598
#undef DRV_VXBEND2_TEI8259X
#undef DRV_VXBEND_TGEC
#undef DRV_VXBEND_TI_EMAC
#undef INCLUDE_UCC_VXB_END
#undef DRV_SIO_UCC
#undef DRV_INTCTLR_VB
#undef DRV_TIMER_VB
#undef DRV_VXBEND_VIARHINE
#undef DRV_INTCTRL_VIOAPIC
#undef DRV_DMA_XLNX
#undef DRV_INTCTLR_XLNX
#undef DRV_VXBEND_XLNX_TEMAC
#undef DRV_SIO_UART_LITE
#undef INCLUDE_XLR_FMN
#undef DRV_PCIBUS_XLS_PCIEX
#undef INCLUDE_XLR_PCI
#undef INCLUDE_MVYUKON_VXB_END
#undef INCLUDE_MVYUKONII_VXB_END
#undef INCLUDE_FLASHFX_DRIVER
#undef INCLUDE_FLASHFX_DISK_0
#undef INCLUDE_FLASHFX_DISK_1
#undef INCLUDE_FLASHFX_DISK_2
#undef INCLUDE_FLASHFX_DISK_3
#undef INCLUDE_FLASHFX_TOOLS
#undef INCLUDE_FLASHFX_TESTS
#undef INCLUDE_VXSIM_USER_SM
#undef DRV_INTCTLR_VXSIM
#undef INCLUDE_HOST_SIO
#undef INCLUDE_WINDMANAGE_SNMP_AGENTX_COMMONCORE
#undef INCLUDE_WINDMANAGE_SNMP_AGENTX_MASTERCORE
#undef INCLUDE_WINDMANAGE_SNMP_AGENTX_SUBAGENTCORE
#undef INCLUDE_WINDMANAGE_SNMP_CORE
#undef INCLUDE_WINDMANAGE_SNMP_V3CORE
#undef INCLUDE_JOB_QUEUE_UTIL
#undef INCLUDE_NET_BOOT_IPV6_CFG
#undef INCLUDE_IPCOM_USE_INET6
#undef INCLUDE_END2_LINKBUFPOOL
#undef INCLUDE_END_POLLED_STATS
#undef INCLUDE_MUX_OVER_END2
#undef INCLUDE_MUXTK_OVER_END2
#undef INCLUDE_MUX_IF_FUNC_DBASE
#undef INCLUDE_NETBUFADVLIB
#undef INCLUDE_NETPOOLSHOW
#undef INCLUDE_MBUF_UTIL2
#undef INCLUDE_NETSTAT_UN_COMP
#undef INCLUDE_NET_INIT
#undef INCLUDE_IP6ATTACH
#undef INCLUDE_XDR_BOOL_T
#undef INCLUDE_VXMUX_PKT_POOL_MIN
#undef INCLUDE_VXMUX_SLAB
#undef INCLUDE_VXMUX_CMD_VXSLAB
#undef INCLUDE_IPPING_CMD
#undef INCLUDE_IPPING6_CMD
#undef INCLUDE_PING6
#undef INCLUDE_IPRADVD
#undef INCLUDE_IPRADVD_CMD
#undef INCLUDE_RLOGIN
#undef INCLUDE_TELNET_CLIENT
#undef INCLUDE_IPTELNETS
#undef INCLUDE_GETSERVBYPORT
#undef INCLUDE_NET_HOST_SHOW
#undef INCLUDE_IPNET_USE_NETLINKSOCK
#undef INCLUDE_GETADDRINFO_SYSCTL
#undef INCLUDE_GETNAMEINFO_SYSCTL
#undef INCLUDE_IPLITE_STACK
#undef INCLUDE_IPL2TP
#undef INCLUDE_IPNET_USE_PPP
#undef INCLUDE_IPNET_USE_SOCKDEV
#undef INCLUDE_IPNET_USE_VLAN
#undef INCLUDE_IPSEND
#undef INCLUDE_IPNET_USE_VLAN_STACKING
#undef INCLUDE_L2CONFIG
#undef INCLUDE_MUX_L2
#undef INCLUDE_IPCOM_USE_LINK_STUB
#undef INCLUDE_IPCOM_USE_INET6_ONLY
#undef INCLUDE_IPNET_USE_NAT
#undef INCLUDE_IPVRRPD
#undef INCLUDE_SSH
#undef INCLUDE_FTP6
#undef INCLUDE_SNMP_STATIC_INIT
#undef INCLUDE_SNMP_DYNAMIC_INIT
#undef INCLUDE_QOS_INGRESS
#undef INCLUDE_WM_SNMP_INIT
#undef INCLUDE_IPWRAP_IFSHOW
#undef INCLUDE_IPWRAP_ROUTECMD
#undef INCLUDE_IPWRAP_NETSTAT
#undef INCLUDE_IPWRAP_PING
#undef INCLUDE_IPWRAP_PING6
#undef INCLUDE_IPWRAP_GETADDRINFO
#undef INCLUDE_IPWRAP_GETNAMEINFO
#undef INCLUDE_IPWRAP_GETHOSTBYNAME
#undef INCLUDE_IPWRAP_GETHOSTBYADDR
#undef INCLUDE_IPWRAP_GETSERVBYNAME
#undef INCLUDE_IPWRAP_GETSERVBYPORT
#undef INCLUDE_IPWRAP_ARP
#undef INCLUDE_IPARP_CMD
#undef INCLUDE_IPWRAP_IFNAME
#undef INCLUDE_IPWRAP_GETIFADDRS
#undef INCLUDE_IPWRAP_SNTPCTIMEGET
#undef INCLUDE_IPSNTPC_API
#undef INCLUDE_IPWRAP_SNTPSCLOCKSET
#undef INCLUDE_IPSNTPS_API
#undef INCLUDE_IPSNTPS
#undef INCLUDE_IPWRAP_SNTPSNSECTOFRACTION
#undef INCLUDE_IPWRAP_IFLIB
#undef INCLUDE_IPWRAP_IFLIB_TEST
#undef INCLUDE_IPWRAP_IF6LIB
#undef INCLUDE_IPWRAP_IF6LIB_TEST
#undef INCLUDE_IPWRAP_OLDROUTELIB
#undef INCLUDE_IPNET6_AUTOCONF_PRIVACY_EXT
#undef INCLUDE_IPPPP
#undef INCLUDE_IPPPPOE
#undef INCLUDE_IPPPPMP
#undef INCLUDE_IPPPP_VJCOMP
#undef INCLUDE_IPPPP_CMD
#undef INCLUDE_IPCOM_SYSLOGD_CMD
#undef INCLUDE_IPCOM_SYSVAR_CMD
#undef INCLUDE_IPCOM_USE_TIME_CMD
#undef INCLUDE_IPECHO_CLIENT_CMD
#undef INCLUDE_IPECHO_SERVER_CMD
#undef INCLUDE_IPD_CMD
#undef INCLUDE_IPNET_CTRL_CMD
#undef INCLUDE_IPMEM_DEBUG_CMD
#undef INCLUDE_IPNAT_CMD
#undef INCLUDE_IPNDP_CMD
#undef INCLUDE_IPNETSTAT_CMD
#undef INCLUDE_IPNSLOOKUP_CMD
#undef INCLUDE_IPROUTE_CMD
#undef INCLUDE_IPSOCKPERF_CMD
#undef INCLUDE_IPSOCKTEST_CMD
#undef INCLUDE_IPSVCONFIG_CMD
#undef INCLUDE_IPTRACE_ROUTE_CMD
#undef INCLUDE_IPTCP_TEST_CMD
#undef INCLUDE_IPVCONFIG_CMD
#undef INCLUDE_IPVERSION_CMD
#undef INCLUDE_IPCOM_USE_VXSHELL_CMD
#undef INCLUDE_IPCOM_USE_MIB2_CMD
#undef INCLUDE_IPCOM_CPU_CMD
#undef INCLUDE_IPCOM_SYSLOGD_USE_LOG_FILE
#undef INCLUDE_USER_CMD
#undef INCLUDE_IPNET_PCAP_CMD
#undef INCLUDE_IPCOM_USE_AUTH
#undef INCLUDE_IPCOM_USE_RAM_DISK
#undef INCLUDE_IPMCP
#undef INCLUDE_IPMCP_USE_IGMP
#undef INCLUDE_IPMCP_USE_MLD
#undef INCLUDE_IPMCAST_PROXY_CMD
#undef INCLUDE_IPQUEUE_CONFIG_CMD
#undef INCLUDE_IPQOS_CMD
#undef INCLUDE_WINDML_ALL
#undef INCLUDE_WINDML_NECESSARY
#undef INCLUDE_WINDML
#undef INCLUDE_HOST_WINDML_GRAPHICS
#undef INCLUDE_IPNET_USE_MCAST_ROUTING
#undef INCLUDE_IPNET6_USE_MCAST_ROUTING
#undef INCLUDE_IPMIP
#undef INCLUDE_IPMIP4
#undef INCLUDE_IPMIP6
#undef INCLUDE_IPRADIUS
#undef INCLUDE_IPRADIUS_CMD
#undef INCLUDE_IPCOM_USE_AUTH_RADIUS
#undef INCLUDE_IPPPP_INTERFACE_CONFIG
#undef INCLUDE_IPPPP_USERS_CONFIG
#undef INCLUDE_MIB2_ALL
#undef INCLUDE_MIB2_ICMP
#undef INCLUDE_MIB2_IFMGT
#undef INCLUDE_MIB2_IP
#undef INCLUDE_MIB2_SYSTEM
#undef INCLUDE_MIB2_TCP
#undef INCLUDE_MIB2_UDP
#undef INCLUDE_IPSSL
#undef INCLUDE_IPCRYPTO
#undef INCLUDE_IPSSL_USE_CMDS
#undef INCLUDE_IPSSL_USE_TEST_CMDS
#undef INCLUDE_IPCRYPTO_USE_CMDS
#undef INCLUDE_IPCRYPTO_USE_TEST_CMDS
#undef INCLUDE_IPNET_IFCONFIG_2
#undef INCLUDE_IPNET_IFCONFIG_3
#undef INCLUDE_IPNET_IFCONFIG_4
#undef INCLUDE_IPAIP_INTERFACE_CONFIGS
#undef INCLUDE_IPNET_USE_WLAN
#undef INCLUDE_IPV6
#undef INCLUDE_IPNET6_PRIVACY_GLOBAL_CONFIGS
#undef INCLUDE_IPNET6_PRIVACY_INTERFACE_CONFIGS
#undef INCLUDE_IPNET_IFQUEUE_FIFO_DEFAULT
#undef INCLUDE_IPFTP_CMD
#undef INCLUDE_IPFTPC
#undef INCLUDE_IPDNSC
#undef INCLUDE_IPSNTP_CMD
#undef INCLUDE_IPNTP_CMD
#undef INCLUDE_IPSYSCTL_CMD
#undef INCLUDE_IPTFTP_CLIENT_CMD
#undef INCLUDE_IPTFTPC
#undef INCLUDE_CGA_CMD
#undef INCLUDE_IPCOM_AUTH_1
#undef INCLUDE_IPCOM_AUTH_2
#undef INCLUDE_IPCOM_AUTH_3
#undef INCLUDE_IPCOM_AUTH_4
#undef INCLUDE_IPCOM_AUTH_5
#undef INCLUDE_IPCOM_AUTH_6
#undef INCLUDE_USE_IPCOM_SHELL
#undef INCLUDE_IPCOM_FS_IPCOM
#undef INCLUDE_IPCOM_FS_NATIVE
#undef INCLUDE_IPCOM_USE_KEY_DB
#undef INCLUDE_IPCRYPTO_USE_KEY_DB_EXAMPLE_KEYS
#undef INCLUDE_IPCOM_KEY_DB_CMD
#undef INCLUDE_IPDHCPR
#undef INCLUDE_IPRIP
#undef INCLUDE_IPRIP_CTRL_CMD
#undef INCLUDE_IPRIP_IFCONFIG_1
#undef INCLUDE_IPRIP_IFCONFIG_2
#undef INCLUDE_IPRIP_IFCONFIG_3
#undef INCLUDE_IPRIP_IFCONFIG_4
#undef INCLUDE_IPRIP_STATIC_ROUTE_1
#undef INCLUDE_IPRIP_STATIC_ROUTE_2
#undef INCLUDE_IPRIP_STATIC_ROUTE_3
#undef INCLUDE_IPSNTP_COMMON
#undef INCLUDE_IPSNTPC
#undef INCLUDE_IPTFTP_COMMON
#undef INCLUDE_IPTFTPS
#undef INCLUDE_IPFTPS
#undef INCLUDE_IPDHCPS
#undef INCLUDE_DSHM_BUS_CTLR_SIM
#undef INCLUDE_DSHM_VXSIM
#undef INCLUDE_DSHM_SVC_TIPC
#undef INCLUDE_DSHM_SVC_TIPC_PRIM
#undef INCLUDE_TIPC_MEDIA_SM


/*** PARAMETERS ***/

#undef  DEFAULT_BOOT_LINE
#define DEFAULT_BOOT_LINE BOOT_LINE_ADRS
#undef  LOCAL_MEM_LOCAL_ADRS
#define LOCAL_MEM_LOCAL_ADRS 0x180000000LL
#undef  LOCAL_MEM_SIZE
#define LOCAL_MEM_SIZE 0x04000000
#undef  LOCAL_MEM_AUTOSIZE
#undef  LOCAL_MEM_PHYS_ADRS
#define LOCAL_MEM_PHYS_ADRS 0x20000000
#undef  LOCAL_UNMAPPED_BASE_ADRS
#define LOCAL_UNMAPPED_BASE_ADRS 0x82000000
#undef  NV_RAM_SIZE
#define NV_RAM_SIZE 0x100
#undef  NV_BOOT_OFFSET
#define NV_BOOT_OFFSET 0
#undef  VEC_BASE_ADRS
#define VEC_BASE_ADRS 0
#undef  EXC_MSG_OFFSET
#define EXC_MSG_OFFSET 0x800
#undef  EXC_MSG_ADRS
#define EXC_MSG_ADRS (BOOT_LINE_ADRS + BOOT_LINE_SIZE)
#undef  BOOT_LINE_SIZE
#define BOOT_LINE_SIZE ROUND_UP (sizeof (BOOT_PARAMS), 0x100)
#undef  BOOT_LINE_ADRS
#define BOOT_LINE_ADRS ((char *) (LOCAL_MEM_LOCAL_ADRS+BOOT_LINE_OFFSET))
#undef  BOOT_LINE_OFFSET
#define BOOT_LINE_OFFSET 0x700
#undef  RESERVED
#define RESERVED 0
#undef  FREE_RAM_ADRS
#define FREE_RAM_ADRS (end)
#undef  ROM_WARM_ADRS
#define ROM_WARM_ADRS (0x0)
#undef  STACK_SAVE
#define STACK_SAVE 0x40
#undef  RAM_HIGH_ADRS
#define RAM_HIGH_ADRS 0xffffffff
#undef  RAM_LOW_ADRS
#define RAM_LOW_ADRS 0x180010000
#undef  ROM_BASE_ADRS
#define ROM_BASE_ADRS 0
#undef  ROM_TEXT_ADRS
#define ROM_TEXT_ADRS (ROM_BASE_ADRS)
#undef  ROM_SIZE
#define ROM_SIZE 0
#undef  USER_I_CACHE_MODE
#define USER_I_CACHE_MODE CACHE_WRITETHROUGH
#undef  USER_D_CACHE_MODE
#define USER_D_CACHE_MODE CACHE_COPYBACK
#undef  USER_I_CACHE_ENABLE
#define USER_I_CACHE_ENABLE
#undef  USER_D_CACHE_ENABLE
#define USER_D_CACHE_ENABLE
#undef  VM_PAGE_SIZE
#define VM_PAGE_SIZE 0x10000
#undef  USER_D_MMU_ENABLE
#define USER_D_MMU_ENABLE
#undef  USER_I_MMU_ENABLE
#define USER_I_MMU_ENABLE
#undef  SYS_CLK_RATE
#define SYS_CLK_RATE 60
#undef  SYS_CLK_RATE_MIN
#define SYS_CLK_RATE_MIN 19
#undef  SYS_CLK_RATE_MAX
#define SYS_CLK_RATE_MAX 100
#undef  AUX_CLK_RATE_MIN
#define AUX_CLK_RATE_MIN 2
#undef  AUX_CLK_RATE_MAX
#define AUX_CLK_RATE_MAX 1000
#undef  NUM_TTY
#define NUM_TTY 1
#undef  CONSOLE_TTY
#define CONSOLE_TTY 0
#undef  CONSOLE_BAUD_RATE
#define CONSOLE_BAUD_RATE 9600
#undef  CLEAR_BSS
#define CLEAR_BSS
#undef  MAX_LIO_CALLS
#define MAX_LIO_CALLS 0
#undef  MAX_AIO_SYS_TASKS
#define MAX_AIO_SYS_TASKS 0
#undef  AIO_TASK_PRIORITY
#define AIO_TASK_PRIORITY 0
#undef  AIO_TASK_STACK_SIZE
#define AIO_TASK_STACK_SIZE 0
#undef  MQ_HASH_SIZE
#define MQ_HASH_SIZE 0
#undef  NUM_SIGNAL_QUEUES
#define NUM_SIGNAL_QUEUES 16
#undef  SPY_TASKS_MAX
#define SPY_TASKS_MAX 200
#undef  TIP_CONFIG_STRING
#define TIP_CONFIG_STRING ""
#undef  TIP_ESCAPE_CHARACTER
#define TIP_ESCAPE_CHARACTER "~"
#undef  ROOT_STACK_SIZE
#define ROOT_STACK_SIZE 20000
#undef  ISR_STACK_SIZE
#define ISR_STACK_SIZE 50000
#undef  INT_LOCK_LEVEL
#define INT_LOCK_LEVEL 0x1
#undef  TASK_USER_EXC_STACK_SIZE
#define TASK_USER_EXC_STACK_SIZE (8192*3)
#undef  TASK_USER_EXC_STACK_OVERFLOW_SIZE
#define TASK_USER_EXC_STACK_OVERFLOW_SIZE 4096
#undef  TASK_USER_EXEC_STACK_OVERFLOW_SIZE
#define TASK_USER_EXEC_STACK_OVERFLOW_SIZE 4096
#undef  TASK_USER_EXEC_STACK_UNDERFLOW_SIZE
#define TASK_USER_EXEC_STACK_UNDERFLOW_SIZE 4096
#undef  TASK_KERNEL_EXEC_STACK_OVERFLOW_SIZE
#define TASK_KERNEL_EXEC_STACK_OVERFLOW_SIZE 4096
#undef  TASK_KERNEL_EXEC_STACK_UNDERFLOW_SIZE
#define TASK_KERNEL_EXEC_STACK_UNDERFLOW_SIZE 4096
#undef  TASK_PRIORITY_SET_COMPATIBLE
#define TASK_PRIORITY_SET_COMPATIBLE FALSE
#undef  WIND_JOBS_MAX
#define WIND_JOBS_MAX 64
#undef  VX_GLOBAL_NO_STACK_FILL
#define VX_GLOBAL_NO_STACK_FILL FALSE
#undef  MAX_REBOOT_HOOKS
#define MAX_REBOOT_HOOKS 8
#undef  ENV_VAR_USE_HOOKS
#define ENV_VAR_USE_HOOKS TRUE
#undef  MAX_ISR_JOBS
#define MAX_ISR_JOBS 16
#undef  JOB_TASK_STACK_SIZE
#define JOB_TASK_STACK_SIZE 8000
#undef  FUNCPTR_OBJ_MEMALLOC_RTN
#define FUNCPTR_OBJ_MEMALLOC_RTN memPartAlignedAlloc
#undef  FUNCPTR_OBJ_MEMFREE_RTN
#define FUNCPTR_OBJ_MEMFREE_RTN memPartFree
#undef  OBJ_MEM_POOL_ID
#define OBJ_MEM_POOL_ID memSysPartId
#undef  OBJ_LIBRARY_OPTIONS
#define OBJ_LIBRARY_OPTIONS 0
#undef  VXEVENTS_OPTIONS
#define VXEVENTS_OPTIONS EVENTS_NONINTERRUPTIBLE
#undef  MEM_PART_DEFAULT_OPTIONS
#define MEM_PART_DEFAULT_OPTIONS (MEM_ALLOC_ERROR_LOG_FLAG | MEM_ALLOC_ERROR_EDR_WARN_FLAG | MEM_BLOCK_ERROR_LOG_FLAG | MEM_BLOCK_ERROR_EDR_WARN_FLAG | MEM_BLOCK_ERROR_SUSPEND_FLAG | MEM_BLOCK_CHECK)
#undef  KERNEL_PROXIMITY_HEAP_SIZE
#define KERNEL_PROXIMITY_HEAP_SIZE 0x1000000
#undef  KERNEL_COMMON_HEAP_INIT_SIZE
#define KERNEL_COMMON_HEAP_INIT_SIZE 0x1000000
#undef  KERNEL_COMMON_HEAP_INCR_SIZE
#define KERNEL_COMMON_HEAP_INCR_SIZE 0x200000
#undef  POSIX_SIGNAL_MODE
#define POSIX_SIGNAL_MODE FALSE
#undef  EDR_PM_ARENA
#define EDR_PM_ARENA pmDefaultArena
#undef  PM_RESERVED_MEM
#define PM_RESERVED_MEM 0x100000
#undef  EDR_ERRLOG_SIZE
#define EDR_ERRLOG_SIZE 0x80000
#undef  EDR_RECORD_SIZE
#define EDR_RECORD_SIZE 4096
#undef  VX_TRAD_SCHED_CONSTANT_RDY_Q
#define VX_TRAD_SCHED_CONSTANT_RDY_Q TRUE
#undef  IOS_POSIX_PSE52_MODE
#define IOS_POSIX_PSE52_MODE FALSE
#undef  NUM_DRIVERS
#define NUM_DRIVERS 20
#undef  NUM_FILES
#define NUM_FILES 50
#undef  MAX_LOG_MSGS
#define MAX_LOG_MSGS 50
#undef  TYLIB_XOFF_PCNT
#define TYLIB_XOFF_PCNT 85
#undef  TYLIB_XON_PCNT
#define TYLIB_XON_PCNT 50
#undef  TYLIB_WRT_THRESHLD
#define TYLIB_WRT_THRESHLD 20
#undef  NUM_RAWFS_FILES
#define NUM_RAWFS_FILES 5
#undef  ERF_MAX_USR_CATEGORIES
#define ERF_MAX_USR_CATEGORIES 16
#undef  ERF_MAX_USR_TYPES
#define ERF_MAX_USR_TYPES 16
#undef  DEVICE_MANAGER_MAX_NUM_DEVICES
#define DEVICE_MANAGER_MAX_NUM_DEVICES 255
#undef  WV_DEFAULT_BUF_MIN
#define WV_DEFAULT_BUF_MIN 4
#undef  WV_DEFAULT_BUF_MAX
#define WV_DEFAULT_BUF_MAX 10
#undef  WV_DEFAULT_BUF_SIZE
#define WV_DEFAULT_BUF_SIZE 0x8000
#undef  WV_DEFAULT_BUF_THRESH
#define WV_DEFAULT_BUF_THRESH 0x4000
#undef  WV_DEFAULT_BUF_OPTIONS
#define WV_DEFAULT_BUF_OPTIONS 0x0
#undef  WV_MAX_LOGS
#define WV_MAX_LOGS 5
#undef  WV_UPLOAD_STACKSIZE
#define WV_UPLOAD_STACKSIZE 5000
#undef  WV_UPLOAD_PRIORITY
#define WV_UPLOAD_PRIORITY 150
#undef  WV_RBUFF_MGR_PRIORITY
#define WV_RBUFF_MGR_PRIORITY 100
#undef  INTERRUPT_STACK_OVERFLOW_SIZE
#define INTERRUPT_STACK_OVERFLOW_SIZE 4096
#undef  INTERRUPT_STACK_UNDERFLOW_SIZE
#define INTERRUPT_STACK_UNDERFLOW_SIZE 4096
#undef  WDB_COMM_PORT
#define WDB_COMM_PORT 0x4321
#undef  WDB_STACK_SIZE
#define WDB_STACK_SIZE 0x2000
#undef  WDB_POOL_SIZE
#define WDB_POOL_SIZE 0x0
#undef  WDB_BP_MAX
#define WDB_BP_MAX 25
#undef  WDB_DPRINTF_MAX_MSGS
#define WDB_DPRINTF_MAX_MSGS 100
#undef  WDB_DPRINTF_MAX_MSG_LENGTH
#define WDB_DPRINTF_MAX_MSG_LENGTH 100
#undef  WDB_GOPHER_TAPE_LEN
#define WDB_GOPHER_TAPE_LEN 1400
#undef  WDB_GOPHER_TAPE_NB
#define WDB_GOPHER_TAPE_NB 10
#undef  WDB_RTP_PRIORITY
#define WDB_RTP_PRIORITY 200
#undef  WDB_MTU
#define WDB_MTU 1500
#undef  WDB_TASK_PRIORITY
#define WDB_TASK_PRIORITY 3
#undef  WDB_TASK_OPTIONS
#define WDB_TASK_OPTIONS VX_UNBREAKABLE | VX_FP_TASK
#undef  WDB_RESTART_TIME
#define WDB_RESTART_TIME 10
#undef  WDB_MAX_RESTARTS
#define WDB_MAX_RESTARTS 5
#undef  WDB_SPAWN_STACK_SIZE
#define WDB_SPAWN_STACK_SIZE 0x5000
#undef  STORE_ABS_SYMBOLS
#define STORE_ABS_SYMBOLS FALSE
#undef  STAT_TBL_HASH_SIZE_LOG2
#define STAT_TBL_HASH_SIZE_LOG2 6
#undef  SYM_TBL_HASH_SIZE_LOG2
#define SYM_TBL_HASH_SIZE_LOG2 8
#undef  RTP_HOOK_TBL_SIZE
#define RTP_HOOK_TBL_SIZE 8
#undef  SYSCALL_HOOK_TBL_SIZE
#define SYSCALL_HOOK_TBL_SIZE 8
#undef  RTP_SIGNAL_QUEUE_SIZE
#define RTP_SIGNAL_QUEUE_SIZE 32
#undef  RTP_HEAP_INIT_SIZE
#define RTP_HEAP_INIT_SIZE 0x10000
#undef  RTP_HEAP_DEFAULT_OPTIONS
#define RTP_HEAP_DEFAULT_OPTIONS (MEM_ALLOC_ERROR_LOG_FLAG | MEM_ALLOC_ERROR_EDR_WARN_FLAG | MEM_BLOCK_ERROR_LOG_FLAG | MEM_BLOCK_ERROR_EDR_FATAL_FLAG | MEM_BLOCK_CHECK)
#undef  RTP_FD_NUM_MAX
#define RTP_FD_NUM_MAX 20
#undef  SD_HOOK_TBL_SIZE
#define SD_HOOK_TBL_SIZE 8
#undef  SHELL_TASK_NAME_BASE
#define SHELL_TASK_NAME_BASE "tShell"
#undef  SHELL_TASK_PRIORITY
#define SHELL_TASK_PRIORITY 1
#undef  SHELL_TASK_OPTIONS
#define SHELL_TASK_OPTIONS (VX_FP_TASK | VX_UNBREAKABLE | COPROCS_ALL | VX_PRIVATE_ENV)
#undef  SHELL_STACK_SIZE
#define SHELL_STACK_SIZE 0x10000
#undef  SHELL_SECURE
#define SHELL_SECURE FALSE
#undef  SHELL_START_AT_BOOT
#define SHELL_START_AT_BOOT TRUE
#undef  SHELL_COMPATIBLE
#define SHELL_COMPATIBLE FALSE
#undef  SHELL_DEFAULT_CONFIG
#define SHELL_DEFAULT_CONFIG "LINE_EDIT_MODE=,LINE_LENGTH=256,STRING_FREE=manual,INTERPRETER=,VXE_PATH=.;/romfs"
#undef  SHELL_FIRST_CONFIG
#define SHELL_FIRST_CONFIG NULL
#undef  SHELL_REMOTE_CONFIG
#define SHELL_REMOTE_CONFIG NULL
#undef  SHELL_MAX_SESSIONS
#define SHELL_MAX_SESSIONS -1
#undef  VXDBG_EVT_TASK_PRIORITY
#define VXDBG_EVT_TASK_PRIORITY 25
#undef  VXDBG_EVT_TASK_OPTIONS
#define VXDBG_EVT_TASK_OPTIONS VX_UNBREAKABLE | VX_FP_TASK
#undef  VXDBG_EVT_TASK_STACK_SIZE
#define VXDBG_EVT_TASK_STACK_SIZE 8192
#undef  PASSFS_CACHE
#define PASSFS_CACHE TRUE
#undef  VXSIM_KERNEL_SYS_MEM_RGN_BASE
#define VXSIM_KERNEL_SYS_MEM_RGN_BASE 0x180000000LL
#undef  VXSIM_KERNEL_SYS_MEM_RGN_SIZE
#define VXSIM_KERNEL_SYS_MEM_RGN_SIZE 0x80000000LL
#undef  VXSIM_RTP_PRIVATE_RGN_BASE
#define VXSIM_RTP_PRIVATE_RGN_BASE 0x200000000LL
#undef  VXSIM_RTP_PRIVATE_RGN_SIZE
#define VXSIM_RTP_PRIVATE_RGN_SIZE 0x100000000LL
#undef  VXSIM_SHARED_RGN_SIZE
#define VXSIM_SHARED_RGN_SIZE 0x100000000LL
#undef  VXSIM_KERNEL_VIRT_POOL_RGN_SIZE
#define VXSIM_KERNEL_VIRT_POOL_RGN_SIZE 0x100000000LL
#undef  NET_JOB_NUM_CFG
#define NET_JOB_NUM_CFG 85
#undef  NET_TASK_PRIORITY
#define NET_TASK_PRIORITY 50
#undef  NET_TASK_OPTIONS
#define NET_TASK_OPTIONS VX_SUPERVISOR_MODE | VX_UNBREAKABLE
#undef  NET_TASK_STACKSIZE
#define NET_TASK_STACKSIZE 10000
#undef  NUM_NET_DAEMONS
#define NUM_NET_DAEMONS 1
#undef  NET_DAEMONS_CPU_AFFINITY
#define NET_DAEMONS_CPU_AFFINITY TRUE
#undef  NETBUF_LEADING_CLSPACE_DRV
#define NETBUF_LEADING_CLSPACE_DRV 64
#undef  APPL_LOG_FD_CFG
#define APPL_LOG_FD_CFG STD_OUT
#undef  APPL_LOG_LEVEL_CFG
#define APPL_LOG_LEVEL_CFG (_LOG_DEC_DFLT | _LOG_LVL_DFLT)
#undef  APPL_KERN_LOG_FD_CFG
#define APPL_KERN_LOG_FD_CFG KERN_LOG_FD
#undef  APPL_KERN_LOG_LEVEL_CFG
#define APPL_KERN_LOG_LEVEL_CFG (_LOG_DEC_DFLT | _LOG_LVL_DFLT)
#undef  FTP_TRANSIENT_MAX_RETRY_COUNT
#define FTP_TRANSIENT_MAX_RETRY_COUNT 100
#undef  FTP_TRANSIENT_RETRY_INTERVAL
#define FTP_TRANSIENT_RETRY_INTERVAL 0
#undef  FTP_TRANSIENT_FATAL
#define FTP_TRANSIENT_FATAL ftpTransientFatal
#undef  FTP_DEBUG_OPTIONS
#define FTP_DEBUG_OPTIONS 0
#undef  FTP_TIMEOUT
#define FTP_TIMEOUT 0
#undef  RSH_STDERR_SETUP_TIMEOUT
#define RSH_STDERR_SETUP_TIMEOUT -1
#undef  REM_NUM_CONN_RETRIALS
#define REM_NUM_CONN_RETRIALS 3
#undef  IFCONFIG_1
#define IFCONFIG_1 "ifname","devname driver","inet driver", "gateway driver"
#undef  IFCONFIG_LOOPBACK
#define IFCONFIG_LOOPBACK "ifname lo0","inet 127.0.0.1/32","inet6 ::1/128","inet6 FF01::1/16"
#undef  INET_IPAIP_IFNAME_LIST
#define INET_IPAIP_IFNAME_LIST ""
#undef  INET_IPAIP_PROBE_WAIT
#define INET_IPAIP_PROBE_WAIT "1"
#undef  INET_IPAIP_PROBE_NUM
#define INET_IPAIP_PROBE_NUM "3"
#undef  INET_IPAIP_PROBE_MIN
#define INET_IPAIP_PROBE_MIN "1"
#undef  INET_IPAIP_PROBE_MAX
#define INET_IPAIP_PROBE_MAX "3"
#undef  INET_IPAIP_ANNOUNCE_WAIT
#define INET_IPAIP_ANNOUNCE_WAIT "2"
#undef  INET_IPAIP_ANNOUNCE_NUM
#define INET_IPAIP_ANNOUNCE_NUM "2"
#undef  INET_IPAIP_ANNOUNCE_INTERVAL
#define INET_IPAIP_ANNOUNCE_INTERVAL "2"
#undef  INET_IPAIP_MAX_CONFLICTS
#define INET_IPAIP_MAX_CONFLICTS "10"
#undef  INET_IPAIP_RATE_LIMIT_INTERVAL
#define INET_IPAIP_RATE_LIMIT_INTERVAL "60"
#undef  INET_IPAIP_DEFEND_INTERVAL
#define INET_IPAIP_DEFEND_INTERVAL "10"
#undef  INET_ENABLE_PROXY_ARP
#define INET_ENABLE_PROXY_ARP "0"
#undef  INET_AUTO_PROXY_ARP
#define INET_AUTO_PROXY_ARP "0"
#undef  INET_IFLIST_ENABLE_PROXY_ARP
#define INET_IFLIST_ENABLE_PROXY_ARP ""
#undef  INET_IFLIST_AUTO_PROXY_ARP
#define INET_IFLIST_AUTO_PROXY_ARP ""
#undef  IPNET_MAX_INPUT_PKTS
#define IPNET_MAX_INPUT_PKTS 32
#undef  IPNET_REASSEMBLY_TIMEOUT
#define IPNET_REASSEMBLY_TIMEOUT 60
#undef  IPNET_CACHE_BUFSIZE
#define IPNET_CACHE_BUFSIZE 0
#undef  IPNET_MEMORY_LIMIT
#define IPNET_MEMORY_LIMIT 16777216
#undef  IPNET_MAX_REASSEMBLY_LIST_LEN
#define IPNET_MAX_REASSEMBLY_LIST_LEN 10
#undef  IPNET_MAX_DGRAM_FRAG_LIST_LEN
#define IPNET_MAX_DGRAM_FRAG_LIST_LEN 100
#undef  INET_MIN_MTU_SIZE
#define INET_MIN_MTU_SIZE 576
#undef  INET_BASE_HOP_LIMIT
#define INET_BASE_HOP_LIMIT "64"
#undef  INET_SEND_GRATUITOUS_ARP
#define INET_SEND_GRATUITOUS_ARP "yes"
#undef  INET_DELETE_ADDR_ON_DUPLICATE_DETECT
#define INET_DELETE_ADDR_ON_DUPLICATE_DETECT "yes"
#undef  INET_MAX_PKTS_PENDING
#define INET_MAX_PKTS_PENDING "3"
#undef  INET_MAX_UNICAST_SOLICIT
#define INET_MAX_UNICAST_SOLICIT "1"
#undef  INET_MAX_MULTICAST_SOLICIT
#define INET_MAX_MULTICAST_SOLICIT "9"
#undef  INET_MAX_APP_SOLICIT
#define INET_MAX_APP_SOLICIT "1"
#undef  INET_BASE_REACHABLE_TIME
#define INET_BASE_REACHABLE_TIME "30"
#undef  INET_BASE_RETRANSMIT_TIME
#define INET_BASE_RETRANSMIT_TIME "1"
#undef  INET_DELAY_FIRST_PROBE_TIME
#define INET_DELAY_FIRST_PROBE_TIME "5"
#undef  INET_NBR_CACHE_TO_LIVE_TIME
#define INET_NBR_CACHE_TO_LIVE_TIME "1200"
#undef  INET_DST_CACHE_TO_LIVE_TIME
#define INET_DST_CACHE_TO_LIVE_TIME "600"
#undef  INET_DISABLE_BROADCAST_FWD
#define INET_DISABLE_BROADCAST_FWD "1"
#undef  INET_ICMP_RATE_LIMIT_BUCKET_SIZE
#define INET_ICMP_RATE_LIMIT_BUCKET_SIZE "100"
#undef  INET_ICMP_RATE_LIMIT_INTERVAL
#define INET_ICMP_RATE_LIMIT_INTERVAL "1000"
#undef  INET_ICMP_REDIRECT_SEND
#define INET_ICMP_REDIRECT_SEND "2"
#undef  INET_ICMP_REDIRECT_RECEIVE
#define INET_ICMP_REDIRECT_RECEIVE "1"
#undef  INET_ICMP_IGNORE_ECHO_REQ
#define INET_ICMP_IGNORE_ECHO_REQ "0"
#undef  INET_ICMP_IGNORE_TIMESTAMP_REQ
#define INET_ICMP_IGNORE_TIMESTAMP_REQ "0"
#undef  INET_ICMP_SEND_TIME_EXCEEDED
#define INET_ICMP_SEND_TIME_EXCEEDED "1"
#undef  INET_ICMP_SEND_DST_UNREACHABLE
#define INET_ICMP_SEND_DST_UNREACHABLE "1"
#undef  INET_ICMP_IGNORE_BROADCAST
#define INET_ICMP_IGNORE_BROADCAST "1"
#undef  TCP_CONN_TIMEOUT
#define TCP_CONN_TIMEOUT 75
#undef  TCP_MAX_RETRANSMITS
#define TCP_MAX_RETRANSMITS 10
#undef  TCP_MSL
#define TCP_MSL 30
#undef  TCP_MAX_MSS
#define TCP_MAX_MSS 0
#undef  TCP_USE_TIMESTAMP
#define TCP_USE_TIMESTAMP 0
#undef  TCP_USE_RFC1122_URGENT_DATA
#define TCP_USE_RFC1122_URGENT_DATA 0
#undef  TCP_SEGMENT_MULTIPLIER
#define TCP_SEGMENT_MULTIPLIER 2
#undef  TCP_LAND_ATTACK_PROTECTION
#define TCP_LAND_ATTACK_PROTECTION 1
#undef  TCP_ALLOW_ZERO_WINDOW
#define TCP_ALLOW_ZERO_WINDOW 0
#undef  TCP_ALLOW_TINY_WINDOW
#define TCP_ALLOW_TINY_WINDOW 1
#undef  TCP_PERSIST_TMO
#define TCP_PERSIST_TMO 0
#undef  TCP_CLAMP_MSS
#define TCP_CLAMP_MSS 0
#undef  TCP_DEFAULT_BACKLOG_SIZE
#define TCP_DEFAULT_BACKLOG_SIZE 5
#undef  IPNET_SOCK_MAX
#define IPNET_SOCK_MAX 1024
#undef  IPNET_SOCK_ANON_PORT_MIN
#define IPNET_SOCK_ANON_PORT_MIN "49152"
#undef  IPNET_SOCK_ANON_PORT_MAX
#define IPNET_SOCK_ANON_PORT_MAX "65535"
#undef  IPNET_SOCK_DEFAULT_SEND_BUFSIZE
#define IPNET_SOCK_DEFAULT_SEND_BUFSIZE "100000"
#undef  IPNET_SOCK_DEFAULT_RECV_BUFSIZE
#define IPNET_SOCK_DEFAULT_RECV_BUFSIZE "60000"
#undef  IPNET_SOCK_ADDR_NOTIFY
#define IPNET_SOCK_ADDR_NOTIFY "1"
#undef  IPNET_ROUTE_MAX_CLONE_COUNT
#define IPNET_ROUTE_MAX_CLONE_COUNT "50000"
#undef  IPCOM_SHELL_PROMPT
#define IPCOM_SHELL_PROMPT "\\i$\\w>"

#endif /* INCprjParamsh */
